#!/bin/sh
#
# datacounter_acct.sh
#
# USAGE:
#   datacounter_acct.sh USER TIMERANGE IN_OCTETS OUT_OCTETS IN_GW OUT_GW STATUS SESSIONID
#
# NOTES:
# - Uses 64-bit value = (GW << 32) + OCTETS
# - Adds per-interim session file (SESSFILE) and accumulates on Stop.
# - Includes strong sanity guards to prevent overflow/garbage attributes from corrupting totals.
# - Logs are written to /var/log/wireless.log (and include range/status/sid).
# - state 파일은 /var/run 아래로 이동: 리부트 시 자동 청소됨.
# - Stop이 안 오는 세션 대비로 /var/run state TTL 청소(가볍게, 1시간에 1번) 포함.
# - InfluxDB에는 현재 세션 누적값이 아니라 직전 Interim 대비 delta 값을 저장.
# - 세션 변경/카운터 감소 시 reset으로 판단하고 현재값을 delta로 저장.
#

# ---------- helpers ----------
numonly() { echo -n "$1" | tr -cd '0-9'; }

# All datacounter logs generated by this script are written here.
LOGFILE="/var/log/wireless.log"
: >> "$LOGFILE" 2>/dev/null || true

log() {
  # Usage: log "message..."
  printf '%s datacounter: %s\n' "$(date '+%b %e %H:%M:%S')" "$*" >> "$LOGFILE" 2>/dev/null
}

# Influx line protocol tag escape (space, comma, equal, backslash)
esc_tag() {
  # tag escape: \ , space =
  printf '%s' "$1" | sed \
    -e 's/\\/\\\\/g' \
    -e 's/,/\\,/g' \
    -e 's/ /\\ /g' \
    -e 's/=/\\=/g'
}

# ---------- InfluxDB helpers (1.8.x) ----------
INFLUX_HOST="192.168.209.210"
INFLUX_PORT="8086"
INFLUX_DB="wifiusage"
INFLUX_PRECISION="s"
INFLUX_TIMEOUT="1"       # seconds
INFLUX_CACHE_SEC="600"   # 10분 캐시 (DB 존재/헬스체크 통과 상태)

# 인증이 켜져 있으면 채우세요 (비우면 인증 없이 동작)
INFLUX_USER=""
INFLUX_PASS=""

INFLUX_BASE="http://${INFLUX_HOST}:${INFLUX_PORT}"
INFLUX_WRITE_URL="${INFLUX_BASE}/write?db=${INFLUX_DB}&precision=${INFLUX_PRECISION}"
INFLUX_QUERY_URL="${INFLUX_BASE}/query"
INFLUX_READY_MARK="/tmp/influx_ready_${INFLUX_DB}.stamp"

curl_influx() {
  if [ -n "$INFLUX_USER" ] && [ -n "$INFLUX_PASS" ]; then
    curl -sS -m "$INFLUX_TIMEOUT" --connect-timeout "$INFLUX_TIMEOUT" -u "${INFLUX_USER}:${INFLUX_PASS}" "$@"
  else
    curl -sS -m "$INFLUX_TIMEOUT" --connect-timeout "$INFLUX_TIMEOUT" "$@"
  fi
}

influx_healthcheck() {
  curl_influx -I "${INFLUX_BASE}/ping" >/dev/null 2>&1 && return 0
  curl_influx "${INFLUX_BASE}/health" >/dev/null 2>&1 && return 0
  return 1
}

influx_db_exists() {
  resp="$(curl_influx -G "${INFLUX_QUERY_URL}" --data-urlencode "q=SHOW DATABASES" 2>/dev/null)"
  echo "$resp" | grep -q "\"name\":\"${INFLUX_DB}\""
}

influx_create_db() {
  curl_influx -G "${INFLUX_QUERY_URL}" --data-urlencode "q=CREATE DATABASE ${INFLUX_DB}" >/dev/null 2>&1
}

influx_prepare() {
  now="$(date +%s)"
  if [ -f "$INFLUX_READY_MARK" ]; then
    last="$(cat "$INFLUX_READY_MARK" 2>/dev/null)"
    [ -z "$last" ] && last=0
    age=$(( now - last ))
    if [ "$age" -ge 0 ] && [ "$age" -lt "$INFLUX_CACHE_SEC" ]; then
      return 0
    fi
  fi

  if ! influx_healthcheck; then
    return 1
  fi

  if ! influx_db_exists; then
    influx_create_db
    influx_db_exists || return 1
  fi

  echo "$now" > "$INFLUX_READY_MARK" 2>/dev/null || true
  return 0
}

influx_write_line() {
  line="$1"
  resp="$(curl_influx -i -H 'Content-Type: text/plain' --data-binary "$line" "${INFLUX_WRITE_URL}" 2>&1)"
  rc=$?

  if [ $rc -ne 0 ]; then
    log "INFLUX WRITE FAIL rc=$rc url=${INFLUX_WRITE_URL} resp=$(echo "$resp" | tr '\n' ' ' | cut -c1-300)"
    return 1
  fi

  echo "$resp" | grep -q " 204 " || {
    log "INFLUX WRITE NON-204 url=${INFLUX_WRITE_URL} resp=$(echo "$resp" | tr '\n' ' ' | cut -c1-300)"
    return 1
  }

  return 0
}

# ---------- args (raw) ----------
RAW_USER="$1"
RAW_RANGE="$2"
RAW_IN_O="$3"
RAW_OUT_O="$4"
RAW_IN_GW="$5"
RAW_OUT_GW="$6"
RAW_STATUS="$7"
RAW_SID="$8"

# ---------- sanitize ----------
USERNAME=$(echo -n "$RAW_USER" | sed 's/[^0-9a-zA-Z.:_-]/X/g')

TIMERANGE=$(echo -n "$RAW_RANGE" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9_-]//g')
IN_OCTETS=$(numonly "$RAW_IN_O");     [ -z "$IN_OCTETS" ] && IN_OCTETS=0
OUT_OCTETS=$(numonly "$RAW_OUT_O");   [ -z "$OUT_OCTETS" ] && OUT_OCTETS=0

IN_GW=$(numonly "$RAW_IN_GW");        [ -z "$IN_GW" ] && IN_GW=0
OUT_GW=$(numonly "$RAW_OUT_GW");      [ -z "$OUT_GW" ] && OUT_GW=0

STATUS="$RAW_STATUS"
SESSIONID="$RAW_SID"
[ -z "$SESSIONID" ] && SESSIONID="nosession"

# ---------- paths (log/base) ----------
BASE="/var/log/radacct/datacounter/$TIMERANGE"
MAXFILE="$BASE/max-octets-$USERNAME"
USEDFILE="$BASE/used-octets-$USERNAME"
SESSFILE="$BASE/used-octets-$USERNAME-$SESSIONID"

# ---------- state (in /var/run => reboot clears) ----------
# InfluxDB delta 계산용 직전 Interim 값 저장 디렉터리.
STATE_ROOT="/var/run/datacounter-state"
STATE_DIR="${STATE_ROOT}/${TIMERANGE}"
mkdir -p "$STATE_DIR" 2>/dev/null || true

# 사용자/range/SID 기준 직전 Interim 값 저장 파일 (v2: per-SID keying, E2).
# per-SID 라 동시 세션 간 PREV 핑퐁(재가산)이 없고, 새 SID 는 자연히 first_point 가 된다.
# 재부팅 시 /var/run(tmpfs) 소거 → 같은 SID 라도 first_point → 카운터도 0 이라 delta 작음(정상).
PREVFILE="${STATE_DIR}/prev-${USERNAME}-${SESSIONID}"

# STOPPED 센티넬: Stop 처리 후 늦게 도착한 Interim 이 SESSFILE 을 되살리는 것을 막는다 (E1).
STOPMARK="${STATE_DIR}/stopped-${USERNAME}-${SESSIONID}"

# 회계 파일 RMW 직렬화 락: interim 의 SESSFILE 누적과 Stop 의 은행이 이 락을 공유해야
# double-count/resurrect 가 없다 (E1). 락 유지 시간은 파일 I/O(수 ms)뿐 — export 는 락 밖.
LOCK="/tmp/datacounter_${TIMERANGE}_${USERNAME}.lock"

# Ensure base dir exists
[ -d "$BASE" ] || mkdir -p "$BASE" 2>/dev/null

# ---------- quota not enabled ----------
[ ! -f "$MAXFILE" ] && exit 0

# ---------- init total file ----------
if [ ! -f "$USEDFILE" ]; then
  echo 0 > "$USEDFILE"
fi

# ---------- state TTL cleanup (lightweight) ----------
CLEAN_STAMP="${STATE_ROOT}/.cleanup_stamp"
NOW_TS="$(date +%s)"
last_clean=0
if [ -f "$CLEAN_STAMP" ]; then
  last_clean="$(cat "$CLEAN_STAMP" 2>/dev/null)"
  [ -z "$last_clean" ] && last_clean=0
fi

if [ $((NOW_TS - last_clean)) -ge 3600 ] 2>/dev/null; then
  echo "$NOW_TS" > "$CLEAN_STAMP" 2>/dev/null || true
  find "$STATE_ROOT" -type f \( -name "prev-*" -o -name "stopped-*" \) -mmin +720 -delete >/dev/null 2>&1 || true
fi

# ---------- sanity guards ----------
MAX_OCTETS=4294967295
[ "$IN_OCTETS" -gt "$MAX_OCTETS" ] && IN_OCTETS=0
[ "$OUT_OCTETS" -gt "$MAX_OCTETS" ] && OUT_OCTETS=0

MAX_GW=100000
if [ "$IN_GW" -gt "$MAX_GW" ] || [ "$OUT_GW" -gt "$MAX_GW" ]; then
  log "DATACOUNTER IGNORE $STATUS user=$USERNAME range=$TIMERANGE sid=$SESSIONID (invalid gigawords in=$IN_GW out=$OUT_GW)"
  exit 0
fi

# ---------- 64-bit current value ----------
CUR_IN=$(( (IN_GW << 32) + IN_OCTETS ))
CUR_OUT=$(( (OUT_GW << 32) + OUT_OCTETS ))
CUR_TOTAL=$(( CUR_IN + CUR_OUT ))

if [ "$CUR_IN" -lt 0 ] || [ "$CUR_OUT" -lt 0 ] || [ "$CUR_TOTAL" -lt 0 ]; then
  log "DATACOUNTER IGNORE $STATUS user=$USERNAME range=$TIMERANGE sid=$SESSIONID (negative calc CUR_IN=$CUR_IN CUR_OUT=$CUR_OUT CUR_TOTAL=$CUR_TOTAL; in_gw=$IN_GW out_gw=$OUT_GW in_o=$IN_OCTETS out_o=$OUT_OCTETS)"
  exit 0
fi

# ---------- STOP zero-guard 는 v2 에서 통합 Stop 핸들러로 흡수됨 ----------
# CUR_TOTAL=0 인 Stop 도 아래 STOP 핸들러의 "SESSFILE(누적 delta) 은행 + 마지막 구간 delta"
# 로직이 그대로 처리한다(FINAL_DELTA = CUR = 0 → SESSFILE 그대로 은행). 별도 분기 불필요.

# ---------- INTERIM ----------
if [ "$STATUS" = "Interim-Update" ]; then

  # ---- if zero, do NOT overwrite SESSFILE, do NOT export influx ----
  # CUR_TOTAL=0 인 Interim 은 사용량 0 으로 보고된 것이므로 SESSFILE(세션 누적값)을
  # 덮어쓰지 않는다. (덮어쓰면 quota 가 초기화되어 무제한 사용 가능해짐)
  # 사용자를 강제 disconnect 하지 않고 그대로 둔다.
  if [ "$CUR_TOTAL" -eq 0 ]; then
    log "DATACOUNTER INTERIM ZERO user=$USERNAME range=$TIMERANGE sid=$SESSIONID"

    # PREVFILE의 ts/sid를 현재 시각으로 갱신한다.
    # in/out/total은 직전 정상값을 그대로 유지해야 다음 정상 Interim에서
    # delta = CUR - PREV_정상값 으로 올바르게 계산된다.
    # (ts만 밀어주지 않으면 zero 구간이 끝난 뒤 delta가 과소 집계됨)
    if [ -f "$PREVFILE" ]; then
      # 기존 in/out/total을 읽어서 ts/sid만 교체한다.
      _p_in="$(grep -E '^in=' "$PREVFILE" 2>/dev/null | tail -n1 | cut -d= -f2 | tr -cd '0-9')"
      _p_out="$(grep -E '^out=' "$PREVFILE" 2>/dev/null | tail -n1 | cut -d= -f2 | tr -cd '0-9')"
      _p_total="$(grep -E '^total=' "$PREVFILE" 2>/dev/null | tail -n1 | cut -d= -f2 | tr -cd '0-9')"
      [ -z "$_p_in" ]    && _p_in=0
      [ -z "$_p_out" ]   && _p_out=0
      [ -z "$_p_total" ] && _p_total=0
      tmp="${PREVFILE}.$$"
      {
        echo "ts=$NOW_TS"
        echo "sid=$SESSIONID"
        echo "in=$_p_in"
        echo "out=$_p_out"
        echo "total=$_p_total"
      } > "$tmp" 2>/dev/null && mv -f "$tmp" "$PREVFILE" 2>/dev/null || true
    fi
    # PREVFILE이 없는 경우(세션 첫 Interim이 zero): 갱신할 기준값이 없으므로 그냥 둔다.
    # 다음 정상 Interim에서 HAS_PREV=0 → FIRST_POINT=1 로 현재값 전체를 delta로 사용한다.

    exit 0
  fi

  # ---- 정상(non-zero) 처리: v2 = delta 계산 → SESSFILE 에 delta 누적(락) → Influx export ----
  # 구버전은 SESSFILE=max(CUR)(high-water)라 카운터 리셋(재부팅)마다 최고봉 에포크 1개만 남겨
  # 과소계상됐다(예: 56G 실사용 → 14G 만 계상). v2 는 InfluxDB 와 동일한 검증된 delta 를
  # SESSFILE 에 누적하므로(아래) 모든 에포크 climb 을 보존한다(used-octets ≈ InfluxDB ≈ 물리 WAN).
  # SESSFILE 쓰기는 아래 delta 계산 후 락 안에서 수행한다(INTERIM 로그도 커밋 성공 후 남긴다).

  # ===== InfluxDB 1.8 export - previous Interim delta =====
  # 기존 CUR_IN / CUR_OUT / CUR_TOTAL 값은 변경하지 않고,
  # Influx 전송용 DELTA_IN / DELTA_OUT / DELTA_TOTAL만 계산한다.
  MEASUREMENT="datacounter_interim_delta"

  # precision=s 이므로 timestamp는 epoch second.
  # 초 단위 저장으로 같은 분(分)에 떨어진 interim/Stop 이 서로를 overwrite 하지 않게 한다
  # (분 단위면 같은 분의 두 포인트가 last-write-wins 로 하나 소실 → 과소계상).
  # 육상 복제는 epoch=s·초 합산이라 이 정밀도와 정확히 일치한다.
  ts_s=$NOW_TS

  PREV_TS=0
  PREV_IN=0
  PREV_OUT=0
  PREV_TOTAL=0
  PREV_SID=""
  HAS_PREV=0
  SIDPREV_TS=0   # per-SID PREVFILE 의 ts(없으면 0). 낙관적 락 토큰 전용(마이그레이션 baseline 과 분리).

  if [ -f "$PREVFILE" ]; then
    PREV_TS="$(grep -E '^ts=' "$PREVFILE" 2>/dev/null | tail -n1 | cut -d= -f2 | tr -cd '0-9')"
    PREV_IN="$(grep -E '^in=' "$PREVFILE" 2>/dev/null | tail -n1 | cut -d= -f2 | tr -cd '0-9')"
    PREV_OUT="$(grep -E '^out=' "$PREVFILE" 2>/dev/null | tail -n1 | cut -d= -f2 | tr -cd '0-9')"
    PREV_TOTAL="$(grep -E '^total=' "$PREVFILE" 2>/dev/null | tail -n1 | cut -d= -f2 | tr -cd '0-9')"
    PREV_SID="$(grep -E '^sid=' "$PREVFILE" 2>/dev/null | tail -n1 | cut -d= -f2)"

    [ -z "$PREV_TS" ] && PREV_TS=0
    [ -z "$PREV_IN" ] && PREV_IN=0
    [ -z "$PREV_OUT" ] && PREV_OUT=0
    [ -z "$PREV_TOTAL" ] && PREV_TOTAL=0

    HAS_PREV=1
    SIDPREV_TS="$PREV_TS"
  fi

  # 배포 전환(transition, 일회성): per-SID PREVFILE 이 없고 구버전 per-USER PREVFILE
  # (prev-USERNAME, SID 없는 옛 포맷)이 남아 있으면 그 값을 delta baseline 으로 승계한다.
  # → 배포 직후 활성 세션의 첫 interim 이 first_point(DELTA=CUR=전체누적)로 튀어 SESSFILE
  #   에 카운터 전체가 재가산되는 스파이크(오탐 락아웃)를 방지. SID 는 현재값으로 덮어
  #   SESSION_CHANGED 억제. 낙관적 락 토큰(SIDPREV_TS)은 0(per-SID 부재) 유지 → 커밋 통과.
  # 재부팅 시엔 /var/run(tmpfs)이 통째로 비어 이 옛 파일도 없으므로 정상 first_point
  #   (카운터도 0 → DELTA 작음)로 동작한다. OLDPREV 는 TTL(720분) sweep 으로 정리된다.
  if [ "$HAS_PREV" -eq 0 ]; then
    OLDPREV="${STATE_DIR}/prev-${USERNAME}"
    if [ -f "$OLDPREV" ]; then
      PREV_TS="$(grep -E '^ts=' "$OLDPREV" 2>/dev/null | tail -n1 | cut -d= -f2 | tr -cd '0-9')"
      PREV_IN="$(grep -E '^in=' "$OLDPREV" 2>/dev/null | tail -n1 | cut -d= -f2 | tr -cd '0-9')"
      PREV_OUT="$(grep -E '^out=' "$OLDPREV" 2>/dev/null | tail -n1 | cut -d= -f2 | tr -cd '0-9')"
      PREV_TOTAL="$(grep -E '^total=' "$OLDPREV" 2>/dev/null | tail -n1 | cut -d= -f2 | tr -cd '0-9')"
      [ -z "$PREV_TS" ] && PREV_TS=0
      [ -z "$PREV_IN" ] && PREV_IN=0
      [ -z "$PREV_OUT" ] && PREV_OUT=0
      [ -z "$PREV_TOTAL" ] && PREV_TOTAL=0
      PREV_SID="$SESSIONID"   # 같은 세션 취급(SESSION_CHANGED 억제) → DELTA=CUR-PREV(작음)
      HAS_PREV=1
    fi
  fi

  FIRST_POINT=0
  SESSION_CHANGED=0
  RESET_IN=0
  RESET_OUT=0
  RESET_TOTAL=0
  RESET_DETECTED=0

  if [ "$HAS_PREV" -eq 0 ]; then
    # 처음 보는 Interim이면 현재값을 첫 구간 사용량으로 저장한다.
    DELTA_IN=$(( CUR_IN ))
    DELTA_OUT=$(( CUR_OUT ))
    DELTA_TOTAL=$(( CUR_TOTAL ))
    FIRST_POINT=1
  else
    if [ -n "$PREV_SID" ] && [ "$PREV_SID" != "$SESSIONID" ]; then
      SESSION_CHANGED=1
      RESET_DETECTED=1

      # 세션이 바뀌면 RADIUS 카운터도 새로 시작한 것으로 보고 현재값을 이번 구간 사용량으로 저장.
      DELTA_IN=$(( CUR_IN ))
      DELTA_OUT=$(( CUR_OUT ))
      DELTA_TOTAL=$(( CUR_TOTAL ))
    else
      # 같은 세션이면 직전 Interim과 차이 계산.
      # 값이 줄어들면 카운터 리셋으로 보고 현재값을 delta로 사용.
      if [ "$CUR_IN" -ge "$PREV_IN" ]; then
        DELTA_IN=$(( CUR_IN - PREV_IN ))
      else
        DELTA_IN=$(( CUR_IN ))
        RESET_IN=1
        RESET_DETECTED=1
      fi

      if [ "$CUR_OUT" -ge "$PREV_OUT" ]; then
        DELTA_OUT=$(( CUR_OUT - PREV_OUT ))
      else
        DELTA_OUT=$(( CUR_OUT ))
        RESET_OUT=1
        RESET_DETECTED=1
      fi

      if [ "$CUR_TOTAL" -ge "$PREV_TOTAL" ]; then
        DELTA_TOTAL=$(( CUR_TOTAL - PREV_TOTAL ))
      else
        DELTA_TOTAL=$(( CUR_TOTAL ))
        RESET_TOTAL=1
        RESET_DETECTED=1
      fi
    fi
  fi

  # 안전장치: delta 음수 방지
  [ "$DELTA_IN" -lt 0 ] 2>/dev/null && DELTA_IN=0
  [ "$DELTA_OUT" -lt 0 ] 2>/dev/null && DELTA_OUT=0
  [ "$DELTA_TOTAL" -lt 0 ] 2>/dev/null && DELTA_TOTAL=0

  # ===== v2: SESSFILE 에 delta 누적 (락 + STOPPED 가드 + 낙관적 동시성 + 성공시 PREV 전진) =====
  # - STOPPED 센티넬 존재 → Stop 이후 늦게 온 interim → SESSFILE 되살리기 방지(E1) → skip(42).
  # - PREVFILE ts 가 락 토큰(BASED_TS=SIDPREV_TS = per-SID PREVFILE ts·부재 0)과 다르면 →
  #   동시/재전송 interim 이 이미 커밋 → 중복 가산 방지(낙관적 동시성) → skip(43).
  # - SESSFILE 쓰기 성공 후에만 PREVFILE 전진(E8): 디스크풀 등 실패 시 PREV 안 밀어
  #   다음 interim 이 같은 delta 를 회수(자가치유) → skip(1, export 안 함).
  # - InfluxDB export 는 아래에서 "커밋(rc=0)된 경우에만" → used-octets 와 lockstep.
  acc_rc=0
  lockf -t 10 "$LOCK" sh -c '
    STOPMARK="$1"; SESSFILE="$2"; PREVFILE="$3"; DELTA_TOTAL="$4"; BASED_TS="$5"
    NOW_TS="$6"; SESSIONID="$7"; CUR_IN="$8"; CUR_OUT="$9"; CUR_TOTAL="${10}"
    [ -f "$STOPMARK" ] && exit 42
    if [ -f "$PREVFILE" ]; then
      curts="$(grep -E "^ts=" "$PREVFILE" 2>/dev/null | tail -n1 | cut -d= -f2 | tr -cd "0-9")"
    else
      curts=""
    fi
    [ -z "$curts" ] && curts=0
    [ -z "$BASED_TS" ] && BASED_TS=0
    [ "$curts" != "$BASED_TS" ] && exit 43
    OLD=$(head -n1 "$SESSFILE" 2>/dev/null | tr -cd "0-9"); [ -z "$OLD" ] && OLD=0
    NEW=$(( OLD + DELTA_TOTAL ))
    # 임시파일은 반드시 점(.)으로 시작해 auth 의 합산 glob(used-octets-USER-*)에 안 걸리게 한다.
    # 같은 디렉터리라 mv 는 원자적. (구버전 "${SESSFILE}.$$" 는 glob 에 걸려 mv 창에서 이중합산 위험.)
    stmp="${SESSFILE%/*}/.dctmp-i.$$"
    if printf "%s\n" "$NEW" > "$stmp" 2>/dev/null && mv -f "$stmp" "$SESSFILE" 2>/dev/null; then
      ptmp="${PREVFILE}.$$"
      { echo "ts=$NOW_TS"; echo "sid=$SESSIONID"; echo "in=$CUR_IN"; echo "out=$CUR_OUT"; echo "total=$CUR_TOTAL"; } > "$ptmp" 2>/dev/null && mv -f "$ptmp" "$PREVFILE" 2>/dev/null || true
      exit 0
    fi
    rm -f "$stmp" 2>/dev/null || true
    exit 1
  ' sh "$STOPMARK" "$SESSFILE" "$PREVFILE" "$DELTA_TOTAL" "$SIDPREV_TS" "$NOW_TS" "$SESSIONID" "$CUR_IN" "$CUR_OUT" "$CUR_TOTAL" || acc_rc=$?

  if [ "$acc_rc" -eq 42 ]; then
    log "DATACOUNTER INTERIM SKIP-STOPPED user=$USERNAME range=$TIMERANGE sid=$SESSIONID (interim after Stop; ignored)"
    exit 0
  fi
  if [ "$acc_rc" -eq 43 ]; then
    log "DATACOUNTER INTERIM SKIP-DUP user=$USERNAME range=$TIMERANGE sid=$SESSIONID (concurrent/dup commit; ignored)"
    exit 0
  fi
  if [ "$acc_rc" -ne 0 ]; then
    log "DATACOUNTER INTERIM WRITE-FAIL user=$USERNAME range=$TIMERANGE sid=$SESSIONID (SESSFILE write failed; PREV not advanced, next interim recovers)"
    exit 0
  fi

  log "DATACOUNTER INTERIM user=$USERNAME range=$TIMERANGE sid=$SESSIONID in=$((CUR_IN/1048576))MB out=$((CUR_OUT/1048576))MB total=$((CUR_TOTAL/1048576))MB delta=$((DELTA_TOTAL/1048576))MB"

  # Influx에는 delta만 기본 필드로 저장하고,
  # 검증/디버깅용으로 current/prev/reset 정보도 함께 저장한다.
  in_bytes=$(( DELTA_IN ))
  out_bytes=$(( DELTA_OUT ))
  total_bytes=$(( DELTA_TOTAL ))

  line="${MEASUREMENT},user=$(esc_tag "$USERNAME"),sid=$(esc_tag "$SESSIONID") in_bytes=${in_bytes}i,out_bytes=${out_bytes}i,total_bytes=${total_bytes}i,current_in_bytes=${CUR_IN}i,current_out_bytes=${CUR_OUT}i,current_total_bytes=${CUR_TOTAL}i,prev_in_bytes=${PREV_IN}i,prev_out_bytes=${PREV_OUT}i,prev_total_bytes=${PREV_TOTAL}i,first_point=${FIRST_POINT}i,session_changed=${SESSION_CHANGED}i,reset=${RESET_DETECTED}i,reset_in=${RESET_IN}i,reset_out=${RESET_OUT}i,reset_total=${RESET_TOTAL}i ${ts_s}"

  # InfluxDB export 는 RADIUS 응답 경로에서 분리(fire-and-forget)한다.
  # wait=yes 라도 스크립트가 즉시 반환하도록 백그라운드 서브셸로 보낸다.
  # 쿼터(SESSFILE/PREVFILE)는 위에서 이미 동기 기록되었으므로 손실되지 않으며,
  # export 의 지연/블로킹이 Accounting-Response 지연 → NAS 재전송 폭주로 번져
  # 다른 세션의 회계까지 무너뜨리는 연쇄장애를 차단한다.
  (
    influx_prepare >/dev/null 2>&1 || true
    influx_write_line "$line" || true
  ) >/dev/null 2>&1 &
  # ===== /Influx export =====

  exit 0
fi

# ---------- STOP (v2: SESSFILE(누적 delta) 은행 + 마지막 구간 delta) ----------
# 구버전은 packet CUR_TOTAL 을 은행했는데, 리셋(재부팅) 후 Stop 이면 CUR 이 SESSFILE(누적)보다
# 작아 high-water 를 잃었다. v2 는 SESSFILE(=Σdelta, 검증된 누적)에 마지막 구간 delta 를 더해
# 은행한다. CUR_TOTAL=0 Stop 도 여기서 처리됨(FINAL_DELTA=0 → SESSFILE 그대로 은행).
# ⚠️ STATUS=Stop 에서만 실행: Start/Accounting-On 등이 흘러들어 STOPMARK 를 세워 그 세션의
#    이후 interim 이 전부 skip(42) 되는 사고를 방지(현 설정은 Stop/Interim 만 호출하나 방어).
if [ "$STATUS" = "Stop" ]; then
STOP_OUT="$(lockf -t 10 "$LOCK" sh -c '
  USERNAME="$1"
  TIMERANGE="$2"
  SESSIONID="$3"
  CUR_IN="$4"
  CUR_OUT="$5"
  CUR_TOTAL="$6"
  LOGFILE="$7"
  STATE_DIR="$8"
  STOPMARK="$9"

  BASE="/var/log/radacct/datacounter/$TIMERANGE"
  USEDFILE="$BASE/used-octets-$USERNAME"
  SESSFILE="$BASE/used-octets-$USERNAME-$SESSIONID"
  PREVFILE="${STATE_DIR}/prev-${USERNAME}-${SESSIONID}"

  # 중복 Stop(재전송) 방지: 이미 STOPPED 면 이 SID 는 이미 은행됨 → 재적립 금지(멱등, E1).
  [ -f "$STOPMARK" ] && exit 0
  # STOPPED 센티넬을 먼저 세워 늦게 도착한 interim 의 SESSFILE 되살리기를 차단(E1).
  : > "$STOPMARK" 2>/dev/null || true

  CUR_TOTAL=$(printf "%s" "$CUR_TOTAL" | tr -cd "0-9"); [ -z "$CUR_TOTAL" ] && CUR_TOTAL=0
  CUR_IN=$(printf "%s" "$CUR_IN" | tr -cd "0-9");       [ -z "$CUR_IN" ] && CUR_IN=0
  CUR_OUT=$(printf "%s" "$CUR_OUT" | tr -cd "0-9");     [ -z "$CUR_OUT" ] && CUR_OUT=0

  # 마지막 구간 delta(마지막 interim → Stop). PREVFILE 기준, 카운터 역행(리셋)이면 CUR.
  # interim 이 한 번도 없던 짧은 세션(PREVFILE 부재)은 전체 CUR 이 이 세션 사용량.
  if [ -f "$PREVFILE" ]; then
    PREV_TOTAL="$(grep -E "^total=" "$PREVFILE" 2>/dev/null | tail -n1 | cut -d= -f2 | tr -cd "0-9")"
    PREV_IN="$(grep -E "^in=" "$PREVFILE" 2>/dev/null | tail -n1 | cut -d= -f2 | tr -cd "0-9")"
    PREV_OUT="$(grep -E "^out=" "$PREVFILE" 2>/dev/null | tail -n1 | cut -d= -f2 | tr -cd "0-9")"
    [ -z "$PREV_TOTAL" ] && PREV_TOTAL=0
    [ -z "$PREV_IN" ] && PREV_IN=0
    [ -z "$PREV_OUT" ] && PREV_OUT=0
    if [ "$CUR_TOTAL" -ge "$PREV_TOTAL" ] 2>/dev/null; then
      FINAL_DELTA=$(( CUR_TOTAL - PREV_TOTAL ))
    else
      FINAL_DELTA=$(( CUR_TOTAL ))
    fi
    if [ "$CUR_IN" -ge "$PREV_IN" ] 2>/dev/null; then
      FINAL_DELTA_IN=$(( CUR_IN - PREV_IN ))
    else
      FINAL_DELTA_IN=$(( CUR_IN ))
    fi
    if [ "$CUR_OUT" -ge "$PREV_OUT" ] 2>/dev/null; then
      FINAL_DELTA_OUT=$(( CUR_OUT - PREV_OUT ))
    else
      FINAL_DELTA_OUT=$(( CUR_OUT ))
    fi
  else
    FINAL_DELTA=$(( CUR_TOTAL ))
    FINAL_DELTA_IN=$(( CUR_IN ))
    FINAL_DELTA_OUT=$(( CUR_OUT ))
  fi
  [ "$FINAL_DELTA" -lt 0 ] 2>/dev/null && FINAL_DELTA=0
  [ "$FINAL_DELTA_IN" -lt 0 ] 2>/dev/null && FINAL_DELTA_IN=0
  [ "$FINAL_DELTA_OUT" -lt 0 ] 2>/dev/null && FINAL_DELTA_OUT=0

  OLD_SESS=$(head -n1 "$SESSFILE" 2>/dev/null | tr -cd "0-9"); [ -z "$OLD_SESS" ] && OLD_SESS=0
  SESS_FINAL=$(( OLD_SESS + FINAL_DELTA ))

  OLD_USED=$(head -n 1 "$USEDFILE" 2>/dev/null | tr -d "\r" | tr -cd "0-9"); [ -z "$OLD_USED" ] && OLD_USED=0
  NEW_USED=$(( OLD_USED + SESS_FINAL ))

  # 임시파일은 점(.) 시작으로 auth 합산 glob(used-octets-USER-*) 회피(interim 과 동일 이유).
  utmp="${USEDFILE%/*}/.dctmp-u.$$"
  banked=0
  if printf "%s\n" "$NEW_USED" > "$utmp" 2>/dev/null && mv -f "$utmp" "$USEDFILE" 2>/dev/null; then
    banked=1
  elif printf "%s\n" "$NEW_USED" > "$USEDFILE" 2>/dev/null; then
    banked=1
  fi
  rm -f "$utmp" 2>/dev/null || true

  # PREVFILE 정리: 세션 종료로 무의미(다음 세션 delta 오염 방지). tmpfs rm 이라 디스크풀에도 성공.
  rm -f "$PREVFILE" 2>/dev/null || true
  # SESSFILE 은 은행 성공 시에만 삭제. 은행 실패(디스크풀 #24 등) 시 남겨서 auth glob 합산으로
  # 세션 값을 보존한다(base 는 안 늘었고 STOPMARK 로 interim 은 skip → 이중가산 없음). 리셋 크론이 정리.
  if [ "$banked" -eq 1 ]; then
    rm -f "$SESSFILE" 2>/dev/null || true
  else
    printf "%s datacounter: %s\n" "$(date "+%b %e %H:%M:%S")" \
"DATACOUNTER STOP BANK-FAIL user=$USERNAME range=$TIMERANGE sid=$SESSIONID (USEDFILE write failed; SESSFILE kept, quota preserved via glob)" >> "$LOGFILE" 2>/dev/null
  fi

  printf "%s datacounter: %s\n" "$(date "+%b %e %H:%M:%S")" \
"DATACOUNTER STOP user=$USERNAME range=$TIMERANGE sid=$SESSIONID \
sess=$((SESS_FINAL/1048576))MB final_delta=$((FINAL_DELTA/1048576))MB accum=$((NEW_USED/1048576))MB" >> "$LOGFILE" 2>/dev/null

  # 마지막 구간 delta 를 메인(락 밖)으로 전달 → fire-and-forget InfluxDB 기록.
  # 중복 Stop 은 위에서 조기 exit 하므로 이 줄에 도달하지 않음(멱등: 재기록 없음).
  echo "DCSTOP $FINAL_DELTA_IN $FINAL_DELTA_OUT $FINAL_DELTA"
  exit 0
' sh \
"$USERNAME" "$TIMERANGE" "$SESSIONID" \
"$CUR_IN" "$CUR_OUT" "$CUR_TOTAL" \
"$LOGFILE" "$STATE_DIR" "$STOPMARK")"

RC=$?

if [ "$RC" -ne 0 ]; then
  log "DATACOUNTER SCRIPT FAIL user=$USERNAME range=$TIMERANGE sid=$SESSIONID rc=$RC"
fi

# ---- Stop 세그먼트(마지막 interim → Stop)를 로컬 InfluxDB 에도 기록 ----
# vessel 로컬 InfluxDB 를 interim+Stop 로 완전하게 만들어 육상 복제본과 수치가 일치하게 한다.
# 서브셸이 락 안에서 계산해 stdout(DCSTOP in out total)으로 넘긴 값을 interim 과 동일 형식/정밀도
# (second)로 fire-and-forget 기록한다. total=0 이면 skip(빈 포인트 방지). 중복 Stop 은 DCSTOP 미출력 → skip(멱등).
STOP_LINE="$(printf '%s\n' "$STOP_OUT" | grep '^DCSTOP ' | tail -n1)"
if [ -n "$STOP_LINE" ]; then
  S_IN="$(echo "$STOP_LINE" | awk '{print $2}' | tr -cd '0-9')";    [ -z "$S_IN" ] && S_IN=0
  S_OUT="$(echo "$STOP_LINE" | awk '{print $3}' | tr -cd '0-9')";   [ -z "$S_OUT" ] && S_OUT=0
  S_TOTAL="$(echo "$STOP_LINE" | awk '{print $4}' | tr -cd '0-9')"; [ -z "$S_TOTAL" ] && S_TOTAL=0
  if [ "$S_TOTAL" -gt 0 ] 2>/dev/null; then
    stopline="datacounter_interim_delta,user=$(esc_tag "$USERNAME"),sid=$(esc_tag "$SESSIONID") in_bytes=${S_IN}i,out_bytes=${S_OUT}i,total_bytes=${S_TOTAL}i,stop_segment=1i ${NOW_TS}"
    (
      influx_prepare >/dev/null 2>&1 || true
      influx_write_line "$stopline" || true
    ) >/dev/null 2>&1 &
  fi
fi
fi

# FreeRADIUS Accounting-Response 지연/미응답 방지를 위해 항상 0 종료.
exit 0