#!/bin/sh
#
# datacounter_acct.sh
#
# USAGE:
#   datacounter_acct.sh USER TIMERANGE IN_OCTETS OUT_OCTETS IN_GW OUT_GW STATUS SESSIONID
#
# NOTES:
# - Uses 64-bit value = (GW << 32) + OCTETS
# - Adds per-interim session file (SESSFILE) and accumulates on Stop.
# - Includes strong sanity guards to prevent overflow/garbage attributes from corrupting totals.
# - Logs are written to /var/log/wireless.log (and include range/status/sid).
# - state 파일은 /var/run 아래로 이동: 리부트 시 자동 청소됨.
# - Stop이 안 오는 세션 대비로 /var/run state TTL 청소(가볍게, 1시간에 1번) 포함.
# - InfluxDB에는 현재 세션 누적값이 아니라 직전 Interim 대비 delta 값을 저장.
# - 세션 변경/카운터 감소 시 reset으로 판단하고 현재값을 delta로 저장.
#

# ---------- helpers ----------
numonly() { echo -n "$1" | tr -cd '0-9'; }

# All datacounter logs generated by this script are written here.
LOGFILE="/var/log/wireless.log"
: >> "$LOGFILE" 2>/dev/null || true

log() {
  # Usage: log "message..."
  printf '%s datacounter: %s\n' "$(date '+%b %e %H:%M:%S')" "$*" >> "$LOGFILE" 2>/dev/null
}

# Influx line protocol tag escape (space, comma, equal, backslash)
esc_tag() {
  # tag escape: \ , space =
  printf '%s' "$1" | sed \
    -e 's/\\/\\\\/g' \
    -e 's/,/\\,/g' \
    -e 's/ /\\ /g' \
    -e 's/=/\\=/g'
}

# ---------- InfluxDB helpers (1.8.x) ----------
INFLUX_HOST="192.168.209.210"
INFLUX_PORT="8086"
INFLUX_DB="wifiusage"
INFLUX_PRECISION="m"
INFLUX_TIMEOUT="1"       # seconds
INFLUX_CACHE_SEC="600"   # 10분 캐시 (DB 존재/헬스체크 통과 상태)

# 인증이 켜져 있으면 채우세요 (비우면 인증 없이 동작)
INFLUX_USER=""
INFLUX_PASS=""

INFLUX_BASE="http://${INFLUX_HOST}:${INFLUX_PORT}"
INFLUX_WRITE_URL="${INFLUX_BASE}/write?db=${INFLUX_DB}&precision=${INFLUX_PRECISION}"
INFLUX_QUERY_URL="${INFLUX_BASE}/query"
INFLUX_READY_MARK="/tmp/influx_ready_${INFLUX_DB}.stamp"

curl_influx() {
  if [ -n "$INFLUX_USER" ] && [ -n "$INFLUX_PASS" ]; then
    curl -sS -m "$INFLUX_TIMEOUT" --connect-timeout "$INFLUX_TIMEOUT" -u "${INFLUX_USER}:${INFLUX_PASS}" "$@"
  else
    curl -sS -m "$INFLUX_TIMEOUT" --connect-timeout "$INFLUX_TIMEOUT" "$@"
  fi
}

influx_healthcheck() {
  curl_influx -I "${INFLUX_BASE}/ping" >/dev/null 2>&1 && return 0
  curl_influx "${INFLUX_BASE}/health" >/dev/null 2>&1 && return 0
  return 1
}

influx_db_exists() {
  resp="$(curl_influx -G "${INFLUX_QUERY_URL}" --data-urlencode "q=SHOW DATABASES" 2>/dev/null)"
  echo "$resp" | grep -q "\"name\":\"${INFLUX_DB}\""
}

influx_create_db() {
  curl_influx -G "${INFLUX_QUERY_URL}" --data-urlencode "q=CREATE DATABASE ${INFLUX_DB}" >/dev/null 2>&1
}

influx_prepare() {
  now="$(date +%s)"
  if [ -f "$INFLUX_READY_MARK" ]; then
    last="$(cat "$INFLUX_READY_MARK" 2>/dev/null)"
    [ -z "$last" ] && last=0
    age=$(( now - last ))
    if [ "$age" -ge 0 ] && [ "$age" -lt "$INFLUX_CACHE_SEC" ]; then
      return 0
    fi
  fi

  if ! influx_healthcheck; then
    return 1
  fi

  if ! influx_db_exists; then
    influx_create_db
    influx_db_exists || return 1
  fi

  echo "$now" > "$INFLUX_READY_MARK" 2>/dev/null || true
  return 0
}

influx_write_line() {
  line="$1"
  resp="$(curl_influx -i -H 'Content-Type: text/plain' --data-binary "$line" "${INFLUX_WRITE_URL}" 2>&1)"
  rc=$?

  if [ $rc -ne 0 ]; then
    log "INFLUX WRITE FAIL rc=$rc url=${INFLUX_WRITE_URL} resp=$(echo "$resp" | tr '\n' ' ' | cut -c1-300)"
    return 1
  fi

  echo "$resp" | grep -q " 204 " || {
    log "INFLUX WRITE NON-204 url=${INFLUX_WRITE_URL} resp=$(echo "$resp" | tr '\n' ' ' | cut -c1-300)"
    return 1
  }

  return 0
}

# ---------- Central InfluxDB export helpers (1.8.x) ----------
# 중앙/가상 서버용. 여러 선박의 동일 USER ID가 중복될 수 있으므로
# measurement를 선박별로 나누지 않고 vessel_imo/user tag로 구분한다.
# DB는 이미 생성되어 있다고 가정하므로 CREATE DATABASE 방어 코드는 넣지 않는다.
CENTRAL_INFLUX_HOST="10.8.128.1"
CENTRAL_INFLUX_PORT="8086"
CENTRAL_INFLUX_DB="wifiusage"
CENTRAL_INFLUX_PRECISION="m"
CENTRAL_INFLUX_TIMEOUT="1"
CENTRAL_INFLUX_CACHE_SEC="600"
CENTRAL_MEASUREMENT="wifi_usage"

# 인증이 켜져 있으면 채우세요 (비우면 인증 없이 동작)
CENTRAL_INFLUX_USER=""
CENTRAL_INFLUX_PASS=""

CENTRAL_INFLUX_BASE="http://${CENTRAL_INFLUX_HOST}:${CENTRAL_INFLUX_PORT}"
CENTRAL_INFLUX_WRITE_URL="${CENTRAL_INFLUX_BASE}/write?db=${CENTRAL_INFLUX_DB}&precision=${CENTRAL_INFLUX_PRECISION}"
CENTRAL_INFLUX_READY_MARK="/tmp/influx_ready_central_${CENTRAL_INFLUX_DB}.stamp"

# vessel_imo 조회용 DB 정보
VESSEL_DB_HOST="192.168.209.210"
VESSEL_DB_PORT="3306"
VESSEL_DB_NAME="radius"
VESSEL_DB_USER="radius"
VESSEL_DB_PASS="radius"
VESSEL_TABLE="vesselinfo"
VESSEL_COLUMN="vessel_imo"
VESSEL_CACHE="/tmp/datacounter_vessel_imo.cache"
VESSEL_FAIL_MARK="/tmp/datacounter_vessel_imo.fail"
VESSEL_CACHE_SEC="3600"
VESSEL_FAIL_CACHE_SEC="300"

mysql_client_bin() {
  command -v mysql 2>/dev/null && return 0
  command -v mariadb 2>/dev/null && return 0
  return 1
}

get_vessel_imo() {
  now="$(date +%s)"

  # 성공 캐시 사용
  if [ -f "$VESSEL_CACHE" ]; then
    cache_ts="$(sed -n '1p' "$VESSEL_CACHE" 2>/dev/null | tr -cd '0-9')"
    cache_val="$(sed -n '2p' "$VESSEL_CACHE" 2>/dev/null | sed 's/[^0-9a-zA-Z.:_-]/X/g')"
    [ -z "$cache_ts" ] && cache_ts=0
    age=$(( now - cache_ts ))
    if [ -n "$cache_val" ] && [ "$age" -ge 0 ] && [ "$age" -lt "$VESSEL_CACHE_SEC" ]; then
      printf '%s' "$cache_val"
      return 0
    fi
  fi

  # 실패 캐시 사용: DB 장애 시 Interim마다 DB 접속 시도하지 않도록 함
  if [ -f "$VESSEL_FAIL_MARK" ]; then
    fail_ts="$(cat "$VESSEL_FAIL_MARK" 2>/dev/null | tr -cd '0-9')"
    [ -z "$fail_ts" ] && fail_ts=0
    age=$(( now - fail_ts ))
    if [ "$age" -ge 0 ] && [ "$age" -lt "$VESSEL_FAIL_CACHE_SEC" ]; then
      return 1
    fi
  fi

  MYSQL_BIN="$(mysql_client_bin)" || {
    echo "$now" > "$VESSEL_FAIL_MARK" 2>/dev/null || true
    log "CENTRAL INFLUX SKIP reason=mysql_client_not_found"
    return 1
  }

  # vesselinfo에는 이 클라이언트 선박의 고유 vessel_imo가 들어 있다고 가정한다.
  vessel_raw="$($MYSQL_BIN \
    -N -B \
    -h "$VESSEL_DB_HOST" \
    -P "$VESSEL_DB_PORT" \
    -u "$VESSEL_DB_USER" \
    --password="$VESSEL_DB_PASS" \
    "$VESSEL_DB_NAME" \
    -e "SELECT ${VESSEL_COLUMN} FROM ${VESSEL_TABLE} WHERE ${VESSEL_COLUMN} IS NOT NULL AND ${VESSEL_COLUMN} <> '' LIMIT 1;" \
    2>/dev/null | head -n 1)"

  vessel_imo="$(printf '%s' "$vessel_raw" | sed 's/[^0-9a-zA-Z.:_-]/X/g')"

  if [ -z "$vessel_imo" ]; then
    echo "$now" > "$VESSEL_FAIL_MARK" 2>/dev/null || true
    log "CENTRAL INFLUX SKIP reason=vessel_imo_not_found db=${VESSEL_DB_HOST}:${VESSEL_DB_PORT}/${VESSEL_DB_NAME}/${VESSEL_TABLE}"
    return 1
  fi

  {
    echo "$now"
    echo "$vessel_imo"
  } > "${VESSEL_CACHE}.$$" 2>/dev/null && mv -f "${VESSEL_CACHE}.$$" "$VESSEL_CACHE" 2>/dev/null || true

  rm -f "$VESSEL_FAIL_MARK" 2>/dev/null || true
  printf '%s' "$vessel_imo"
  return 0
}

curl_central_influx() {
  if [ -n "$CENTRAL_INFLUX_USER" ] && [ -n "$CENTRAL_INFLUX_PASS" ]; then
    curl -sS -m "$CENTRAL_INFLUX_TIMEOUT" --connect-timeout "$CENTRAL_INFLUX_TIMEOUT" -u "${CENTRAL_INFLUX_USER}:${CENTRAL_INFLUX_PASS}" "$@"
  else
    curl -sS -m "$CENTRAL_INFLUX_TIMEOUT" --connect-timeout "$CENTRAL_INFLUX_TIMEOUT" "$@"
  fi
}

central_influx_prepare() {
  now="$(date +%s)"
  if [ -f "$CENTRAL_INFLUX_READY_MARK" ]; then
    last="$(cat "$CENTRAL_INFLUX_READY_MARK" 2>/dev/null)"
    [ -z "$last" ] && last=0
    age=$(( now - last ))
    if [ "$age" -ge 0 ] && [ "$age" -lt "$CENTRAL_INFLUX_CACHE_SEC" ]; then
      return 0
    fi
  fi

  # 중앙 DB는 이미 생성되어 있다고 가정. health/ping만 확인한다.
  curl_central_influx -I "${CENTRAL_INFLUX_BASE}/ping" >/dev/null 2>&1 || return 1

  echo "$now" > "$CENTRAL_INFLUX_READY_MARK" 2>/dev/null || true
  return 0
}

central_influx_write_line() {
  line="$1"
  resp="$(curl_central_influx -i -H 'Content-Type: text/plain' --data-binary "$line" "${CENTRAL_INFLUX_WRITE_URL}" 2>&1)"
  rc=$?

  if [ $rc -ne 0 ]; then
    log "CENTRAL INFLUX WRITE FAIL rc=$rc url=${CENTRAL_INFLUX_WRITE_URL} resp=$(echo "$resp" | tr '\n' ' ' | cut -c1-300)"
    return 1
  fi

  echo "$resp" | grep -q " 204 " || {
    log "CENTRAL INFLUX WRITE NON-204 url=${CENTRAL_INFLUX_WRITE_URL} resp=$(echo "$resp" | tr '\n' ' ' | cut -c1-300)"
    return 1
  }

  return 0
}

central_influx_export_usage() {
  vessel_imo="$(get_vessel_imo)" || return 1

  # 필수 구분자 외 sid/debug 문자열은 넣지 않는다.
  # 중앙 저장 구조:
  #   measurement: wifi_usage
  #   tags: vessel_imo, user
  #   fields: in_bytes, out_bytes, total_bytes (숫자 only)
  line="${CENTRAL_MEASUREMENT},vessel_imo=$(esc_tag "$vessel_imo"),user=$(esc_tag "$USERNAME") in_bytes=${in_bytes}i,out_bytes=${out_bytes}i,total_bytes=${total_bytes}i ${ts_m}"

  central_influx_prepare >/dev/null 2>&1 || return 1
  central_influx_write_line "$line"
}

# ---------- args (raw) ----------
RAW_USER="$1"
RAW_RANGE="$2"
RAW_IN_O="$3"
RAW_OUT_O="$4"
RAW_IN_GW="$5"
RAW_OUT_GW="$6"
RAW_STATUS="$7"
RAW_SID="$8"

# ---------- sanitize ----------
USERNAME=$(echo -n "$RAW_USER" | sed 's/[^0-9a-zA-Z.:_-]/X/g')

TIMERANGE=$(echo -n "$RAW_RANGE" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9_-]//g')
IN_OCTETS=$(numonly "$RAW_IN_O");     [ -z "$IN_OCTETS" ] && IN_OCTETS=0
OUT_OCTETS=$(numonly "$RAW_OUT_O");   [ -z "$OUT_OCTETS" ] && OUT_OCTETS=0

IN_GW=$(numonly "$RAW_IN_GW");        [ -z "$IN_GW" ] && IN_GW=0
OUT_GW=$(numonly "$RAW_OUT_GW");      [ -z "$OUT_GW" ] && OUT_GW=0

STATUS="$RAW_STATUS"
SESSIONID="$RAW_SID"
[ -z "$SESSIONID" ] && SESSIONID="nosession"

# ---------- paths (log/base) ----------
BASE="/var/log/radacct/datacounter/$TIMERANGE"
MAXFILE="$BASE/max-octets-$USERNAME"
USEDFILE="$BASE/used-octets-$USERNAME"
SESSFILE="$BASE/used-octets-$USERNAME-$SESSIONID"

# ---------- state (in /var/run => reboot clears) ----------
# InfluxDB delta 계산용 직전 Interim 값 저장 디렉터리.
STATE_ROOT="/var/run/datacounter-state"
STATE_DIR="${STATE_ROOT}/${TIMERANGE}"
mkdir -p "$STATE_DIR" 2>/dev/null || true

# 사용자/range 기준 직전 Interim 값 저장 파일.
# SESSIONID를 일부러 빼서 세션 재시작 후 카운터가 작아지는 상황도 감지한다.
PREVFILE="${STATE_DIR}/prev-${USERNAME}"

# Ensure base dir exists
[ -d "$BASE" ] || mkdir -p "$BASE" 2>/dev/null

# ---------- quota not enabled ----------
[ ! -f "$MAXFILE" ] && exit 0

# ---------- init total file ----------
if [ ! -f "$USEDFILE" ]; then
  echo 0 > "$USEDFILE"
fi

# ---------- state TTL cleanup (lightweight) ----------
CLEAN_STAMP="${STATE_ROOT}/.cleanup_stamp"
NOW_TS="$(date +%s)"
last_clean=0
if [ -f "$CLEAN_STAMP" ]; then
  last_clean="$(cat "$CLEAN_STAMP" 2>/dev/null)"
  [ -z "$last_clean" ] && last_clean=0
fi

if [ $((NOW_TS - last_clean)) -ge 3600 ] 2>/dev/null; then
  echo "$NOW_TS" > "$CLEAN_STAMP" 2>/dev/null || true
  find "$STATE_ROOT" -type f -name "prev-*" -mmin +720 -delete >/dev/null 2>&1 || true
fi

# ---------- sanity guards ----------
MAX_OCTETS=4294967295
[ "$IN_OCTETS" -gt "$MAX_OCTETS" ] && IN_OCTETS=0
[ "$OUT_OCTETS" -gt "$MAX_OCTETS" ] && OUT_OCTETS=0

MAX_GW=100000
if [ "$IN_GW" -gt "$MAX_GW" ] || [ "$OUT_GW" -gt "$MAX_GW" ]; then
  log "DATACOUNTER IGNORE $STATUS user=$USERNAME range=$TIMERANGE sid=$SESSIONID (invalid gigawords in=$IN_GW out=$OUT_GW)"
  exit 0
fi

# ---------- 64-bit current value ----------
CUR_IN=$(( (IN_GW << 32) + IN_OCTETS ))
CUR_OUT=$(( (OUT_GW << 32) + OUT_OCTETS ))
CUR_TOTAL=$(( CUR_IN + CUR_OUT ))

if [ "$CUR_IN" -lt 0 ] || [ "$CUR_OUT" -lt 0 ] || [ "$CUR_TOTAL" -lt 0 ]; then
  log "DATACOUNTER IGNORE $STATUS user=$USERNAME range=$TIMERANGE sid=$SESSIONID (negative calc CUR_IN=$CUR_IN CUR_OUT=$CUR_OUT CUR_TOTAL=$CUR_TOTAL; in_gw=$IN_GW out_gw=$OUT_GW in_o=$IN_OCTETS out_o=$OUT_OCTETS)"
  exit 0
fi

# ---------- STOP zero-guard ----------
# CUR_TOTAL=0 으로 Stop 이 오는 경우(로그아웃 없이 WiFi/LAN 절단 등):
# NAS 가 최종 사용량을 0 으로 보고하므로, 아래 lockf STOP 섹션의 누적 로직을
# 그대로 타면 마지막 SESSFILE 값이 USEDFILE 에 반영되지 않고 사라진다.
# 따라서 여기서 SESSFILE 값을 USEDFILE 에 누적한 뒤 정리하고 종료한다.
if [ "$STATUS" = "Stop" ] && [ "$CUR_TOTAL" -eq 0 ]; then
  # PREVFILE 정리: 세션 종료이므로 다음 세션의 delta 오염 방지
  rm -f "$PREVFILE" 2>/dev/null || true

  # SESSFILE 정리: 마지막 Interim 이 non-zero 였다면 SESSFILE 이 남아있다.
  # 이 파일을 삭제하지 않으면 다음 인증 시 datacounter_auth.sh 의 glob 이
  # 구 세션 bytes 를 합산해 quota 합계가 부풀려지는 버그가 발생한다.
  # 단, USEDFILE 에 반영되지 않은 bytes 이므로 먼저 USEDFILE 에 누적한 후 삭제한다.
  if [ -f "$SESSFILE" ]; then
    LAST_SESS=$(head -n1 "$SESSFILE" 2>/dev/null | tr -cd '0-9')
    [ -z "$LAST_SESS" ] && LAST_SESS=0
    if [ "$LAST_SESS" -gt 0 ]; then
      # USEDFILE 에 마지막 세션 bytes 반영 (atomic)
      lockf -t 10 "/tmp/datacounter_${TIMERANGE}_${USERNAME}.lock" sh -c '
        USEDFILE="$1"; LAST_SESS="$2"
        OLD=$(head -n1 "$USEDFILE" 2>/dev/null | tr -cd "0-9")
        [ -z "$OLD" ] && OLD=0
        NEW=$(( OLD + LAST_SESS ))
        printf "%s\n" "$NEW" > "$USEDFILE"
      ' sh "$USEDFILE" "$LAST_SESS" 2>/dev/null || true
    fi
    rm -f "$SESSFILE" 2>/dev/null || true
  fi

  log "DATACOUNTER STOP-ZERO user=$USERNAME range=$TIMERANGE sid=$SESSIONID (zero octets; session usage preserved)"
  exit 0
fi

# ---------- INTERIM ----------
if [ "$STATUS" = "Interim-Update" ]; then

  # ---- if zero, do NOT overwrite SESSFILE, do NOT export influx ----
  # CUR_TOTAL=0 인 Interim 은 사용량 0 으로 보고된 것이므로 SESSFILE(세션 누적값)을
  # 덮어쓰지 않는다. (덮어쓰면 quota 가 초기화되어 무제한 사용 가능해짐)
  # 사용자를 강제 disconnect 하지 않고 그대로 둔다.
  if [ "$CUR_TOTAL" -eq 0 ]; then
    log "DATACOUNTER INTERIM ZERO user=$USERNAME range=$TIMERANGE sid=$SESSIONID"

    # PREVFILE의 ts/sid를 현재 시각으로 갱신한다.
    # in/out/total은 직전 정상값을 그대로 유지해야 다음 정상 Interim에서
    # delta = CUR - PREV_정상값 으로 올바르게 계산된다.
    # (ts만 밀어주지 않으면 zero 구간이 끝난 뒤 delta가 과소 집계됨)
    if [ -f "$PREVFILE" ]; then
      # 기존 in/out/total을 읽어서 ts/sid만 교체한다.
      _p_in="$(grep -E '^in=' "$PREVFILE" 2>/dev/null | tail -n1 | cut -d= -f2 | tr -cd '0-9')"
      _p_out="$(grep -E '^out=' "$PREVFILE" 2>/dev/null | tail -n1 | cut -d= -f2 | tr -cd '0-9')"
      _p_total="$(grep -E '^total=' "$PREVFILE" 2>/dev/null | tail -n1 | cut -d= -f2 | tr -cd '0-9')"
      [ -z "$_p_in" ]    && _p_in=0
      [ -z "$_p_out" ]   && _p_out=0
      [ -z "$_p_total" ] && _p_total=0
      tmp="${PREVFILE}.$$"
      {
        echo "ts=$NOW_TS"
        echo "sid=$SESSIONID"
        echo "in=$_p_in"
        echo "out=$_p_out"
        echo "total=$_p_total"
      } > "$tmp" 2>/dev/null && mv -f "$tmp" "$PREVFILE" 2>/dev/null || true
    fi
    # PREVFILE이 없는 경우(세션 첫 Interim이 zero): 갱신할 기준값이 없으므로 그냥 둔다.
    # 다음 정상 Interim에서 HAS_PREV=0 → FIRST_POINT=1 로 현재값 전체를 delta로 사용한다.

    exit 0
  fi

  # ---- 정상(non-zero) 처리: SESSFILE 기록 + 로그 + Influx export ----
  echo "$CUR_TOTAL" > "$SESSFILE"

  log "DATACOUNTER INTERIM user=$USERNAME range=$TIMERANGE sid=$SESSIONID in=$((CUR_IN/1048576))MB out=$((CUR_OUT/1048576))MB total=$((CUR_TOTAL/1048576))MB"

  # ===== InfluxDB 1.8 export - previous Interim delta =====
  # 기존 CUR_IN / CUR_OUT / CUR_TOTAL 값은 변경하지 않고,
  # Influx 전송용 DELTA_IN / DELTA_OUT / DELTA_TOTAL만 계산한다.
  MEASUREMENT="datacounter_interim_delta"

  # precision=m 이므로 timestamp는 epoch minute.
  # 기존 10분 bucket은 같은 tag/timestamp 포인트를 overwrite할 수 있어 현재 minute로 저장한다.
  ts_m=$(( NOW_TS / 60 ))

  PREV_TS=0
  PREV_IN=0
  PREV_OUT=0
  PREV_TOTAL=0
  PREV_SID=""
  HAS_PREV=0

  if [ -f "$PREVFILE" ]; then
    PREV_TS="$(grep -E '^ts=' "$PREVFILE" 2>/dev/null | tail -n1 | cut -d= -f2 | tr -cd '0-9')"
    PREV_IN="$(grep -E '^in=' "$PREVFILE" 2>/dev/null | tail -n1 | cut -d= -f2 | tr -cd '0-9')"
    PREV_OUT="$(grep -E '^out=' "$PREVFILE" 2>/dev/null | tail -n1 | cut -d= -f2 | tr -cd '0-9')"
    PREV_TOTAL="$(grep -E '^total=' "$PREVFILE" 2>/dev/null | tail -n1 | cut -d= -f2 | tr -cd '0-9')"
    PREV_SID="$(grep -E '^sid=' "$PREVFILE" 2>/dev/null | tail -n1 | cut -d= -f2)"

    [ -z "$PREV_TS" ] && PREV_TS=0
    [ -z "$PREV_IN" ] && PREV_IN=0
    [ -z "$PREV_OUT" ] && PREV_OUT=0
    [ -z "$PREV_TOTAL" ] && PREV_TOTAL=0

    HAS_PREV=1
  fi

  FIRST_POINT=0
  SESSION_CHANGED=0
  RESET_IN=0
  RESET_OUT=0
  RESET_TOTAL=0
  RESET_DETECTED=0

  if [ "$HAS_PREV" -eq 0 ]; then
    # 처음 보는 Interim이면 현재값을 첫 구간 사용량으로 저장한다.
    DELTA_IN=$(( CUR_IN ))
    DELTA_OUT=$(( CUR_OUT ))
    DELTA_TOTAL=$(( CUR_TOTAL ))
    FIRST_POINT=1
  else
    if [ -n "$PREV_SID" ] && [ "$PREV_SID" != "$SESSIONID" ]; then
      SESSION_CHANGED=1
      RESET_DETECTED=1

      # 세션이 바뀌면 RADIUS 카운터도 새로 시작한 것으로 보고 현재값을 이번 구간 사용량으로 저장.
      DELTA_IN=$(( CUR_IN ))
      DELTA_OUT=$(( CUR_OUT ))
      DELTA_TOTAL=$(( CUR_TOTAL ))
    else
      # 같은 세션이면 직전 Interim과 차이 계산.
      # 값이 줄어들면 카운터 리셋으로 보고 현재값을 delta로 사용.
      if [ "$CUR_IN" -ge "$PREV_IN" ]; then
        DELTA_IN=$(( CUR_IN - PREV_IN ))
      else
        DELTA_IN=$(( CUR_IN ))
        RESET_IN=1
        RESET_DETECTED=1
      fi

      if [ "$CUR_OUT" -ge "$PREV_OUT" ]; then
        DELTA_OUT=$(( CUR_OUT - PREV_OUT ))
      else
        DELTA_OUT=$(( CUR_OUT ))
        RESET_OUT=1
        RESET_DETECTED=1
      fi

      if [ "$CUR_TOTAL" -ge "$PREV_TOTAL" ]; then
        DELTA_TOTAL=$(( CUR_TOTAL - PREV_TOTAL ))
      else
        DELTA_TOTAL=$(( CUR_TOTAL ))
        RESET_TOTAL=1
        RESET_DETECTED=1
      fi
    fi
  fi

  # 안전장치: delta 음수 방지
  [ "$DELTA_IN" -lt 0 ] 2>/dev/null && DELTA_IN=0
  [ "$DELTA_OUT" -lt 0 ] 2>/dev/null && DELTA_OUT=0
  [ "$DELTA_TOTAL" -lt 0 ] 2>/dev/null && DELTA_TOTAL=0

  # 다음 Interim 비교를 위해 현재값 저장
  tmp="${PREVFILE}.$$"
  {
    echo "ts=$NOW_TS"
    echo "sid=$SESSIONID"
    echo "in=$CUR_IN"
    echo "out=$CUR_OUT"
    echo "total=$CUR_TOTAL"
  } > "$tmp" 2>/dev/null && mv -f "$tmp" "$PREVFILE" 2>/dev/null || true

  # Influx에는 delta만 기본 필드로 저장하고,
  # 검증/디버깅용으로 current/prev/reset 정보도 함께 저장한다.
  in_bytes=$(( DELTA_IN ))
  out_bytes=$(( DELTA_OUT ))
  total_bytes=$(( DELTA_TOTAL ))

  line="${MEASUREMENT},user=$(esc_tag "$USERNAME"),sid=$(esc_tag "$SESSIONID") in_bytes=${in_bytes}i,out_bytes=${out_bytes}i,total_bytes=${total_bytes}i,current_in_bytes=${CUR_IN}i,current_out_bytes=${CUR_OUT}i,current_total_bytes=${CUR_TOTAL}i,prev_in_bytes=${PREV_IN}i,prev_out_bytes=${PREV_OUT}i,prev_total_bytes=${PREV_TOTAL}i,first_point=${FIRST_POINT}i,session_changed=${SESSION_CHANGED}i,reset=${RESET_DETECTED}i,reset_in=${RESET_IN}i,reset_out=${RESET_OUT}i,reset_total=${RESET_TOTAL}i ${ts_m}"

  influx_prepare >/dev/null 2>&1 || true
  influx_write_line "$line" || true

  # 중앙/가상 InfluxDB export.
  # sid/range는 저장하지 않고 vessel_imo/user + 숫자 사용량만 저장한다.
  central_influx_export_usage || true
  # ===== /Influx export =====

  exit 0
fi

# ---------- STOP / others ----------
LOCK="/tmp/datacounter_${TIMERANGE}_${USERNAME}.lock"

lockf -t 10 "$LOCK" sh -c '
  USERNAME="$1"
  TIMERANGE="$2"
  SESSIONID="$3"
  CUR_IN="$4"
  CUR_OUT="$5"
  CUR_TOTAL="$6"
  IN_GW="$7"
  OUT_GW="$8"
  LOGFILE="$9"
  STATE_DIR="${10}"

  BASE="/var/log/radacct/datacounter/$TIMERANGE"
  USEDFILE="$BASE/used-octets-$USERNAME"
  SESSFILE="$BASE/used-octets-$USERNAME-$SESSIONID"

  # PREVFILE 정리: Stop 수신 시 다음 세션의 첫 Interim이 잘못된 prev 값을
  # 참조하지 않도록 반드시 삭제한다.
  PREVFILE="${STATE_DIR}/prev-${USERNAME}"
  rm -f "$PREVFILE" 2>/dev/null || true

  OLD_TOTAL=$(head -n 1 "$USEDFILE" 2>/dev/null | tr -d "\r" | tr -cd "0-9")
  CUR_TOTAL=$(printf "%s" "$CUR_TOTAL" | tr -cd "0-9")
  CUR_IN=$(printf "%s" "$CUR_IN" | tr -cd "0-9")
  CUR_OUT=$(printf "%s" "$CUR_OUT" | tr -cd "0-9")

  [ -z "$OLD_TOTAL" ] && OLD_TOTAL=0
  [ -z "$CUR_TOTAL" ] && CUR_TOTAL=0
  [ -z "$CUR_IN" ] && CUR_IN=0
  [ -z "$CUR_OUT" ] && CUR_OUT=0

  NEW_TOTAL=$(( ${OLD_TOTAL:-0} + ${CUR_TOTAL:-0} ))

  [ -f "$SESSFILE" ] && rm -f "$SESSFILE"
  printf "%s\n" "$NEW_TOTAL" > "$USEDFILE"

  printf "%s datacounter: %s\n" "$(date "+%b %e %H:%M:%S")" \
"DATACOUNTER STOP user=$USERNAME range=$TIMERANGE sid=$SESSIONID \
in=$((CUR_IN/1048576))MB out=$((CUR_OUT/1048576))MB \
total=$((CUR_TOTAL/1048576))MB accum=$((NEW_TOTAL/1048576))MB" >> "$LOGFILE" 2>/dev/null

  exit 0
' sh \
"$USERNAME" "$TIMERANGE" "$SESSIONID" \
"$CUR_IN" "$CUR_OUT" "$CUR_TOTAL" \
"$IN_GW" "$OUT_GW" "$LOGFILE" "$STATE_DIR"

RC=$?

if [ "$RC" -ne 0 ]; then
  log "DATACOUNTER SCRIPT FAIL user=$USERNAME range=$TIMERANGE sid=$SESSIONID rc=$RC"
fi

# FreeRADIUS Accounting-Response 지연/미응답 방지를 위해 항상 0 종료.
exit 0